import assert from 'node:assert/strict'
import { CruiseConnectClient, MemoryQueueStore } from '../packages/sdk/src/index.ts'
import { ReferenceCruiseHost } from '../packages/reference-host/src/index.ts'

const host=new ReferenceCruiseHost(), store=new MemoryQueueStore(), sdk=new CruiseConnectClient(host,store)
const session=await sdk.initialize()
assert.equal(session.ageBand,'adult')
assert.equal((await sdk.events()).length,3)
assert.equal((await sdk.meetups()).length,2)
await sdk.updateInterests(['wine','photography','wine'])
await sdk.joinMeetup('meet-wine')
const passengerImage=new Uint8Array([1,2,3,4,5]), passenger=await sdk.identifyPassenger(passengerImage)
assert.equal(passenger.status,'recognized');assert.deepEqual([...passengerImage],[0,0,0,0,0])
await sdk.sendVibe(passenger.receiverToken!,'made-my-day')
const crewImage=new Uint8Array([2,3,4,5]), crew=await sdk.identifyCrew(crewImage)
await sdk.recognizeCrew(crew.receiverToken!,['warm-welcome'])
await sdk.submitEventFeedback({eventId:'evt-jazz',score:5,responseIds:['great-atmosphere','right-length']})
await sdk.setNotifications(true)
await sdk.notify('evt-jazz','Jazz starts soon','Meet your group in the Atrium.','2026-09-01T19:45:00+02:00')
const attributionRef=await sdk.purchase('wine-tasting','food-beverage')
await sdk.recordPurchase({attributionRef,status:'confirmed',value:49,currency:'EUR'})
assert.equal(host.actions.length,7);assert.equal(host.notifications.length,1);assert.equal(host.purchases.length,1)
host.setOffline(true)
const queued=await sdk.updateInterests(['jewellery'])
assert.equal(queued.queued,true);assert.equal(await sdk.queued(),1)
host.setOffline(false)
assert.deepEqual(await sdk.flush(),{sent:1,remaining:0})
host.setMinor(true)
const minorSdk=new CruiseConnectClient(host)
await minorSdk.initialize()
assert.equal((await minorSdk.identifyPassenger(new Uint8Array([1,2,3,4]))).status,'ineligible')
console.log('CruiseConnect SDK end-to-end contract passed.')
